### ISSUE TITLE
Remove character '_' from domainNameLabel

### ISSUE THREAD

**Issue by fberson** [mmarch/rds-templates#12] opened 2016-12-01 14:46 UTC
Although I never advise it, it is possible to have an underscore in the name of a resource group. When running the RDS farm deployment in such a resourcegroup it fails because the **domainNameLabel** is constructed based on the resourcegroup name.

```
"apiVersion": "2015-06-15",
"type": "Microsoft.Network/publicIPAddresses",
"name": "[variables('gatewayIpRef')]",
"location": "[resourceGroup().location]",
"properties": {
  "publicIPAllocationMethod": "Dynamic",
  "dnsSettings": {
  "domainNameLabel": "[variables('gwdnsLabelPrefix')]"

"gwdnsLabelPrefix": "[concat('gwd', resourceGroup().name)]",
```

We might want to avoid this situation and add a function to remove underscores (or add this naming requirement in the documentation somewhere).

For example by replacing this:
`"gwdnsLabelPrefix": "[concat('gwd', resourceGroup().name)]",`
By this
`"gwdnsLabelPrefix": "[concat('gwd', replace(resourceGroup().name,'_',''))]", `

Or by introducing a new variables that we can use throughout the template like this:
```
"resourceGroupNameTrimmed": "[replace(resourceGroup().name,'_','')]",
"gwdnsLabelPrefix": "[concat('gwd', variables('resourceGroupNameTrimmed'))]",
```

**Comment by mmarch** [comment] 2017-03-13 19:14
We shouldn't use resourcegroup().name in dns labels at all (rather use uniquestring(resourceGroup().id) instead as per [Best Practices guidelines for Resources:  domainNameLabels (#5)](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-template-best-practices).

Closing as duplicate of #35.

**Closed as completed by mmarch** 2017-03-13 19:14 UTC
Labels: duplicate
